___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [264]:
import numpy as np


### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [2]:
my_list = [5, 10, 15, 20, 25]
np.array(my_list)


array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [5]:
np.ones((4,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [10]:
np.ones((4,4))*7


array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

### 6. Create the previous array above by full() method.

In [7]:
np.full((4,4),7)


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [15]:
np.arange(2 , 17, 2)


array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [19]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [29]:
np.linspace(0,24,25, dtype = "int").reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 10. Create randomly 5 numbers with numpy.

In [30]:
np.random.rand(5)

array([0.76180233, 0.9514974 , 0.59237304, 0.91670984, 0.88393209])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [36]:
np.random.randn(5,5)

array([[-0.26447257,  1.45740137, -0.44877658, -0.27624822, -0.18378814],
       [-0.83512489,  1.338653  , -0.06758991, -0.77733192,  0.07254674],
       [-0.55117924, -0.13128013, -0.91209227, -0.41723076,  0.85583694],
       [-0.90138032,  0.28952089,  0.43898061, -0.74858096,  0.76190921],
       [ 1.44773981, -1.39220368,  0.50188405,  0.00858048, -1.17925441]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [38]:
np.random.randint(20,50, size = (3, 4))


array([[20, 38, 45, 21],
       [26, 31, 42, 45],
       [21, 37, 29, 41]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [43]:
ranarr=np.random.randint(48, size = 48)
print(ranarr)

[38  7 26 18 42 42 19 13 13 46 38 26 40  4 14  9 35 43 13  2 25 18  5 26
 44 38 10  1 41 40  5 30 34 41  5  1 40 38 44 10 17  7 45 34 42 29 25 47]


In [44]:
ranarr=np.random.randint(48, size = 48).reshape(6,8)
print(ranarr)

[[22  8  4  8 21 17 47 30]
 [29  2 20 27 13 30 23 11]
 [36 28 45 31  9 38 35 10]
 [44 40 44 46 28 30 12 12]
 [45  3 16  6  3 34 34 32]
 [30  8 46 43  3 23 46  0]]


In [47]:
ranarr=np.random.randint(48, size = 48).reshape(4,12)
print(ranarr)

[[21 40 46 31 21 27 15 10 42 45 25 28]
 [ 0 33 13 12  0 38 22 19 28 24  1 29]
 [41  3 39 41 47 23  6 21 38 17 41 16]
 [31 35  1 46 10 15 20 39  9  2 43  0]]


In [48]:
ranarr=np.random.randint(48, size = 48).reshape(3,16)
print(ranarr)


[[19 32 12 11 30 23 47 39 26 43 32 38  2 11 11 46]
 [20 25 34 21 40 10 19 41 45 45  8 23 35 29 31 18]
 [39 12 11 21 40 39 28 15 38 45 32  2 43 36 35 45]]


## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [53]:
mat=np.arange(1,17).reshape(4,4)
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [62]:
# YOUR CODE IS HERE 
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [67]:
# YOUR CODE IS HERE 
mat[:,0]

array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [72]:
# YOUR CODE IS HERE 


### 17.Assign 77 to every cell in 3rd column.

In [77]:
# YOUR CODE IS HERE 
mat[:,2]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [91]:
# YOUR CODE IS HERE 


array([], shape=(1, 0), dtype=int64)

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [88]:
# YOUR CODE IS HERE 


SyntaxError: invalid syntax (<ipython-input-88-1440e0e23955>, line 2)

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [92]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [100]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 

# YOUR CODE IS HERE 

values=mat[mat<10]
print(values)


[1 2 4 5 6 8 9]


In [101]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 
values=mat[mat>12]
print(values)


[77 77 77 13 14 77 16]


In [104]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 


[]


### 21. Get the standard deviation (std) of the result above.

In [110]:
# YOUR CODE IS HERE 
x=np.array([78, 79, 81, 18, 20, 85, 25])
x.std()


29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [111]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [113]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat=np.array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])


In [125]:
# YOUR CODE IS HERE 
mat[:,1].sum()


32

### 23. Get the median, mean and std of 3rd column in "mat".

In [126]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [129]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 
x=mat[:,2]
x

array([ 3,  7, 11, 15])

In [135]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

# YOUR CODE IS HERE 

y=mat[2,:]
y

array([ 9, 10, 11, 12])

In [136]:
# LET US GET MEDIAN VALUE 

# YOUR CODE IS HERE 
np.median(x)
np.median(y)

10.5

In [138]:
# LET US GET MEAN VALUE 

# YOUR CODE IS HERE 

np.mean(x)
np.median(y)

10.5

In [142]:
# LET US GET STANDART DEVIATION (std) VALUE 

# YOUR CODE IS HERE 

np.std(x)
np.std(y)


1.118033988749895

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [148]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [149]:
# LET US READ Salaries.csv 

# YOUR CODE IS HERE 
data=pd.read_csv("Salaries.csv")


In [150]:
# LET US LOOK AT THE FIRST 5 ROWS 

# YOUR CODE IS HERE 

data.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [152]:
# LET US GET A SAMPLE 

# YOUR CODE IS HERE 
data.sample()


Id EmployeeName      JobTitle  BasePay  OvertimePay  OtherPay  \
34951  34952  NEIL CARMAN  JUNIOR CLERK   1677.6          0.0       0.0   

       Benefits  TotalPay  TotalPayBenefits  Year  Notes         Agency  \
34951       NaN    1677.6            1677.6  2011    NaN  San Francisco   

       Status  
34951     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [153]:
# YOUR CODE IS HERE 

type(data)

pandas.core.frame.DataFrame

In [154]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

# YOUR CODE IS HERE 

data.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [167]:
# YOUR CODE IS HERE 

data.groupby("Year")["Id"].count().

Year
2011    36159
2012    36766
2013    37606
2014    38123
Name: Id, dtype: int64

In [169]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 

data["Year"].nunique()

4

In [170]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 
data["Year"].unique()


array([2011, 2012, 2013, 2014])

### Print out max and avg values in the column of "Totalpay".

In [172]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE 

data["TotalPay"].max()

567595.43

In [173]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE 
data["TotalPay"].mean()


74768.321971703

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [194]:
# YOUR CODE IS HERE 

x=data[data["TotalPay"]>74768.321971703]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [203]:
# YOUR CODE IS HERE 

x.count()

Id                  69489
EmployeeName        69489
JobTitle            69489
BasePay             69480
OvertimePay         69489
OtherPay            69489
Benefits            53642
TotalPay            69489
TotalPayBenefits    69489
Year                69489
Notes                   0
Agency              69489
Status                  0
dtype: int64

### How much does ALBERT PARDINI make money (including benefits)?

In [210]:
# YOUR CODE IS HERE 
data[data["EmployeeName"]=="ALBERT PARDINI"]["TotalPayBenefits"]


2    335279.91
Name: TotalPayBenefits, dtype: float64

### Who is the lowest paid person?

In [221]:
# YOUR CODE IS HERE 
data["TotalPayBenefits"].sort_index(ascending=False)
data[data["Id"]==148654]

Id EmployeeName                    JobTitle  BasePay  OvertimePay  \
148653  148654    Joe Lopez  Counselor, Log Cabin Ranch      0.0          0.0   

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
148653   -618.13       0.0   -618.13           -618.13  2014    NaN   

               Agency  Status  
148653  San Francisco     NaN

### What are the unique Jobs in dataset?

In [228]:
data["JobTitle"].unique()


array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [452]:
# YOUR CODE IS HERE 
data.groupby("JobTitle").agg({"Id":"count"}).sort_values(by="Id")
data.groupby("JobTitle").agg({"Id":"count"})==1


Id
JobTitle                                             
ACCOUNT CLERK                                   False
ACCOUNTANT                                      False
ACCOUNTANT INTERN                               False
ACPO,JuvP, Juv Prob (SFERS)                      True
ACUPUNCTURIST                                    True
...                                               ...
X-RAY LABORATORY AIDE                           False
X-Ray Laboratory Aide                           False
YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS   True
Youth Comm Advisor                              False
ZOO CURATOR                                      True

[2159 rows x 1 columns]

### How many people earned more than avg in 2012?

In [282]:
# YOUR CODE IS HERE 
data[(data["TotalPayBenefits"] > data["TotalPayBenefits"].mean()) & (data["Year"]==2012)]["Id"].count()


20366

### How many people have a title of Manager in their jobs?

In [458]:
# USE APPLY FUNCTION

# YOUR CODE IS HERE 

#data.loc[data["JobTitle"].apply(lambda x: x.contains('Manager').any())]
data.loc[data['JobTitle'].str.contains("Manager", case=False)].count()



Id                  4110
EmployeeName        4110
JobTitle            4110
BasePay             4097
OvertimePay         4110
OtherPay            4110
Benefits            3080
TotalPay            4110
TotalPayBenefits    4110
Year                4110
Notes                  0
Agency              4110
Status                 0
dtype: int64

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [350]:
# YOUR CODE IS HERE 

sal_new=data.loc[:,["Id","EmployeeName","JobTitle","TotalPay","TotalPayBenefits"]]
sal_new


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [433]:
# YOUR CODE IS HERE 
sal_new.iloc[:,1:5]


EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [431]:
# YOUR CODE IS HERE 
df=data[data["TotalPayBenefits"] < (data["TotalPayBenefits"].mean())]
df[["EmployeeName","TotalPayBenefits"]]
df=df[:-1]
df


Id    EmployeeName             JobTitle   BasePay  OvertimePay  \
10806    10807         KWE LEE  AUTOMOTIVE MECHANIC  72198.10      6017.76   
10807    10808  MIGUEL CARO JR  STATIONARY ENGINEER  72420.69      2665.79   
10808    10809   JOANNE MORRIS     REGISTERED NURSE  91672.69         0.00   
10809    10810   LAYLA WELBORN        SPECIAL NURSE  80683.54      8809.03   
10810    10811         LE BANH     TRANSIT OPERATOR  67349.30     23507.62   
...        ...             ...                  ...       ...          ...   
148648  148649     Leon Walker            Custodian      0.00         0.00   
148649  148650   Roy I Tillery            Custodian      0.00         0.00   
148650  148651    Not provided         Not provided       NaN          NaN   
148651  148652    Not provided         Not provided       NaN          NaN   
148652  148653    Not provided         Not provided       NaN          NaN   

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
10806   15475.29       NaN  93691.15          93691.15  2011    NaN   
10807   18596.26       NaN  93682.74          93682.74  2011    NaN   
10808    2007.84       NaN  93680.53          93680.53  2011    NaN   
10809    4184.31       NaN  93676.88          93676.88  2011    NaN   
10810    2818.47       NaN  93675.39          93675.39  2011    NaN   
...          ...       ...       ...               ...   ...    ...   
148648      0.00       0.0      0.00              0.00  2014    NaN   
148649      0.00       0.0      0.00              0.00  2014    NaN   
148650       NaN       NaN      0.00              0.00  2014    NaN   
148651       NaN       NaN      0.00              0.00  2014    NaN   
148652       NaN       NaN      0.00              0.00  2014    NaN   

               Agency  Status  
10806   San Francisco     NaN  
10807   San Francisco     NaN  
10808   San Francisco     NaN  
10809   San Francisco     NaN  
10810   San Francisco     NaN  
...               ...     ...  
148648  San Francisco     NaN  
148649  San Francisco     NaN  
148650  San Francisco     NaN  
148651  San Francisco     NaN  
148652  San Francisco     NaN  

[75649 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________